name: mlflow-retrain

on:
  push:
    paths:
      - '.workflow/**'
      - 'MLProject/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: MLProject
    env:
      DOCKER_IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==3.5.1 scikit-learn==1.7.2 pandas==2.3.3 numpy==2.3.4

      - name: Run MLflow Project
        env:
          MLFLOW_HOME: ${{ github.workspace }}/MLProject
        run: |
          mlflow run . --env-manager=local --experiment-name ci_random_forest

      - name: Validate Docker Hub secrets
        run: |
          if [ -z "$DOCKERHUB_USERNAME" ] || [ -z "$DOCKERHUB_TOKEN" ] || [ -z "$DOCKERHUB_REPOSITORY" ]; then
            echo "Rahasiakan dan isi rahasia DOCKERHUB_USERNAME, DOCKERHUB_TOKEN, dan DOCKERHUB_REPOSITORY sebelum menjalankan workflow."
            exit 1
          fi
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image with MLflow
        run: |
          python build_docker_image.py \
            --experiment-name ci_random_forest \
            --image-name "${DOCKERHUB_REPOSITORY}:${DOCKER_IMAGE_TAG}" \
            --tracking-uri "file:${{ github.workspace }}/MLProject/mlruns" \
            --model-artifact model
        env:
          DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }}

      - name: Push Docker image
        run: |
          docker push "${DOCKERHUB_REPOSITORY}:${DOCKER_IMAGE_TAG}"
          docker tag "${DOCKERHUB_REPOSITORY}:${DOCKER_IMAGE_TAG}" "${DOCKERHUB_REPOSITORY}:latest"
          docker push "${DOCKERHUB_REPOSITORY}:latest"
        env:
          DOCKERHUB_REPOSITORY: ${{ secrets.DOCKERHUB_REPOSITORY }}

      - name: Archive MLflow artifacts
        run: |
          tar -czf mlruns.tar.gz mlruns || echo "No mlruns directory generated"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-runs
          path: MLProject/mlruns.tar.gz
          if-no-files-found: warn
