name: mlflow-retrain

on:
  push:
    paths:
      - 'Workflow-CI/**'
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Workflow-CI/MLProject

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==3.5.1 scikit-learn==1.7.2 pandas==2.3.3 numpy==2.3.4

      - name: Run MLflow Project
        env:
          MLFLOW_HOME: ${{ github.workspace }}/Workflow-CI/MLProject
        run: |
          mlflow run . --env-manager=local --experiment-name ci_random_forest

      - name: Archive MLflow artifacts
        run: |
          tar -czf mlruns.tar.gz mlruns || echo "No mlruns directory generated"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-runs
          path: Workflow-CI/MLProject/mlruns.tar.gz
          if-no-files-found: warn
